---
- name: "Setting up NetworkManager configuration"
  hosts: localhost
  tasks:
    - name: "Setting up IPv6 Privacy Extension"
      become: true
      ansible.builtin.copy:
        content: |
          [connections]
          ipv6.ip6-privacy=2
        dest: /etc/NetworkManager/conf.d/10-ip6-privacy.conf
        force: false
        mode: '0600'
      notify: Reload NetworkManager
  handlers:
    - name: Reload NetworkManager
      become: true
      ansible.builtin.command: nmcli general reload
      notify: Disable networking

    - name: Disable networking
      ansible.builtin.command: nmcli networking off
      notify: Enable networking

    - name: Enable networking
      ansible.builtin.command: nmcli networking on
      notify: Wait for network to start
    # FIX: This prints empty lines in playbook's output screen. Figure out how to remove it (or add a loading animation if possible)
    - name: Wait for network to start
      ansible.builtin.command: nmcli networking connectivity
      register: connectivity
      until: connectivity.stdout == "full"
      changed_when: false

- name: Setting up DNF packages
  hosts: localhost
  become: true
  tasks:
    - name: Removing packaes
      ansible.builtin.dnf:
        name:
          - nano
          - hplip
          - firefox
          - xarchiver
        state: absent
        allowerasing: true
        autoremove: true
    - name: Swapping Fedora Release Packages for Sway's
      ansible.builtin.dnf:
        name:
          - fedora-release-sway
          - fedora-release-identity-sway
        state: latest
        allowerasing: true
    - name: Installing packages
      ansible.builtin.dnf:
        name:
          - nvim
          - fish
          - flatpak
          - toolbox
          - git
        state: latest
    - name: Installing LibreWolf
      ansible.builtin.import_tasks: tasks/install_librewolf.ansible.yml
    - name: Installing Mullvad Browser
      ansible.builtin.import_tasks: tasks/install_mullvad-browser.ansible.yml
    # - name: Installing 3rd-Party Packages
    #   vars:
    #     packges:
    #       - { repo_url: "https://repo.librewolf.net/librewolf.repo", package: "librewolf"}
    #       - { repo_url: "https://repository.mullvad.net/rpm/stable/mullvad.repo", package: mullvad-browser}
    #   ansible.builtin.include_tasks:
    #     file: tasks/install_thirdparty_software.ansible.yml
    #   loop: "{{ packges }}"
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

- name: RPMFusion Playbook
  ansible.builtin.import_playbook: playbooks/rpmfusion.ansible.yml

- name: Flatpak Playbook
  ansible.builtin.import_playbook: playbooks/flatpak.ansible.yml

- name: Disabling services/daemons
  hosts: localhost
  become: true
  tasks:
    - name: Stop service shhd.socket
      ansible.builtin.service:
        name: sshd.socket
        enabled: false
        state: stopped
    - name: Stop service sshd.service
      ansible.builtin.service:
        name: sshd.service
        enabled: false
        state: stopped

- name: Setting configuration
  hosts: localhost
  vars:
    dotfile_dir: "{{ playbook_dir }}/dotfiles"
    cache_stow_file: "{{ dotfile_dir }}/.cache_stow"
    dotfile_paths:
      - "{{ ansible_env.HOME }}/.config"
      - "{{ ansible_env.HOME }}/.bashrc"
      - "{{ ansible_env.HOME }}/.local/share/flatpak/overrides"
      - "{{ ansible_env.HOME }}/.bash_profile"
  tasks:
    - name: Setting dotfiles
      ansible.builtin.include_tasks:
        file: dotfiles.ansible.yml
      loop: "{{ dotfile_paths }}"
...
