---
- name: Automatize DNF Updates
  hosts: localhost
  become: true
  tasks:
    - name: Install DNF Automatic
      ansible.builtin.dnf:
        name: dnf-automatic
        state: present
      register: install_dnfautomatic

    - name: Enable and Start DNF Automatic Systemd Service
      when: install_dnfautomatic is success
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        enabled: true
        state: started
        daemon_reload: true
